# f=open("geek.txt",'r')
# print("File Name : ",f.name)
# print("Mode : ",f.mode)
# print("Size : ",f.__sizeof__())
# print(f.closed)
# d=open("../../hell.txt")
# d=open("../basicpy/hell.txt")
# print(d.name)
#how to read data from file
f=open("geek.txt")
content=f.read()
print(content)
r=open("calculator.cpp")
content=r.read()
print(content)
